version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - STORAGE_TYPE=postgres
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      - PORT=8080
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data: