// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        string     `json:"id"`
	PostID    string     `json:"postID"`
	ParentID  *string    `json:"parentID,omitempty"`
	Author    string     `json:"author"`
	Text      string     `json:"text"`
	CreatedAt string     `json:"createdAt"`
	Replies   []*Comment `json:"replies"`
}

type Mutation struct {
}

type Post struct {
	ID            string     `json:"id"`
	Title         string     `json:"title"`
	Content       string     `json:"content"`
	Author        string     `json:"author"`
	AllowComments bool       `json:"allowComments"`
	CreatedAt     string     `json:"createdAt"`
	Comments      []*Comment `json:"comments"`
}

type Query struct {
}

type Subscription struct {
}
